---
#configuring web server

-name: deploying configuration file
 copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
 notify: restart apache 


# Add sample html file
- name: deploy index.html
  copy:
   src: index.html
   dest: /var/www/html/index.html