---

# Setup LAMP stack
 - hosts: dev
   become: yes
   tasks:
    - name: install lamp stack
      
      apt:
       pkg:
        - apache2
        - mysql-server
        - php
        - php-mysql
       state: latest
       update_cache: yes
    
    - name: start apache service
      service:
       name: apache2
       state: started
       enabled: yes

    - name: start mysql service
      service: 
       name: mysql
       state: started
       enabled: yes
    
    - name: creat target directory
      file: path=/var/www/html state=directory mode=0755

    - name: deploy index.html
      copy:
       src: /tmp/index.html
       dest: /var/www/html/index.html

...